### ISSUE TITLE
Em que direção você está indo?

### ISSUE THREAD

**Issue by jonasmalacofilho** [vgeorge/monitor-de-velocidades#1]
Opa Vitor, beleza?

Tenho um interesse tremendo por esse tipo de coisa e já fiz algo (possivelmente) [parecido](https://github.com/jonasmalacofilho/big-speed), com dados históricos de outra cidade) e queria entender melhor o que você está fazendo.  (há uns meses até peguei dados históricos de SP para testar uma nova versão daquilo, mais rápida e precisa, mas isso ainda está na minha lista de TODOs)

O que você pretende obter?  Velocidades médias das linhas, ou (dos trechos) das vias?  Ou ambos?  Só atuais ou também históricas?

Se quiser, vamos marcar outro café para conversar sobre o assunto (se você ainda estiver em SP)...

**Comment by vgeorge** [comment]
Fala Jonas! A idéia geral é obter os vetores de deslocamentos a partir da API do Olho Vivo, "projetá-los" nas vias em que a rota passa e com isso determinar as velocidades médias das vias e das rotas. A versão inicial armazenaria um período curto (talvez uma hora) de observações de algumas linhas, para que não sejam necessários muitos recursos. 

Podemos marcar uma conversa sim, meu e-mail é vitor.george@gmail.com. Nos mês de outubro estou querendo organizar um hack night em um espaço novo que vamos ocupar, seria legal conversar com mais gente. Te aviso, se for rolar.

**Comment by jonasmalacofilho** [comment]
Legal cara!  Adoraria ajudá-los...

Não quer aparecer aqui no escritório um dia?  Emendamos um happy hour...  (estamos a duas quadras do Garoa)

**Comment by vgeorge** [comment]
Não tenho o seu contato, me manda um e-mail e combinamos?
